# Numpy

In [84]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
getallen = [2,5,3,8,5,6]
getallen

[2, 5, 3, 8, 5, 6]

In [13]:
a = np.array(getallen)
a

array([2, 5, 3, 8, 5, 6])

In [14]:
type(a)

numpy.ndarray

In [15]:
a.dtype

dtype('int64')

In [16]:
a.ndim

1

In [17]:
len(a)

6

In [19]:
a.shape

(6,)

In [27]:
m = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
m.shape

(3, 3)

In [30]:
np.array(range(27)).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
a = np.array([1,2,3,4,5,6,7,8]).reshape(4, 2).T
a

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [37]:
np.arange(1, 28, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5])

In [42]:
np.linspace(1, 28, 55).reshape(11, 5)

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5, 13. ],
       [13.5, 14. , 14.5, 15. , 15.5],
       [16. , 16.5, 17. , 17.5, 18. ],
       [18.5, 19. , 19.5, 20. , 20.5],
       [21. , 21.5, 22. , 22.5, 23. ],
       [23.5, 24. , 24.5, 25. , 25.5],
       [26. , 26.5, 27. , 27.5, 28. ]])

In [46]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## Indexing and Slicing

In [48]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [49]:
a[4]

4

In [50]:
a[6:12]

array([ 6,  7,  8,  9, 10, 11])

In [51]:
a[-5:]

array([22, 23, 24, 25, 26])

In [52]:
m = np.arange(24).reshape(4, 6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [56]:
m[-1, 2]

20

In [59]:
m[-2:, 2:]

array([[14, 15, 16, 17],
       [20, 21, 22, 23]])

In [62]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [64]:
mask = [True, False, False, True, True, False, True]
a[mask]

array([0, 3, 4, 6])

In [65]:
fancy_index = [6,2,4,3,1]
a[fancy_index]

array([6, 2, 4, 3, 1])

## Vectorized

In [75]:
getallen

[2, 5, 3, 8, 5, 6]

In [70]:
a = np.array(getallen)
a

array([2, 5, 3, 8, 5, 6])

In [71]:
a * 2

array([ 4, 10,  6, 16, 10, 12])

In [74]:
a ** 2

array([ 4, 25,  9, 64, 25, 36])

In [77]:
a + np.array([1,2,3,4,5,6])

array([ 3,  7,  6, 12, 10, 12])

## Unary ufuncs

In [79]:
x = np.linspace(0, 10, 101)

In [92]:
y1 = np.sin(x)
y2 = np.cos(2*x)

In [93]:
plt.plot(x, y1)
plt.plot(x, y2)

plt.show()

In [96]:
z = np.add(y1, y2)

In [97]:
plt.plot(x, z)
plt.show()

In [98]:
a

array([2, 5, 3, 8, 5, 6])

In [99]:
a > 4

array([False,  True, False,  True,  True,  True])

In [100]:
a[a > 4]

array([5, 8, 5, 6])

In [104]:
a[(a > 4) & (a < 7)]

array([5, 5, 6])

In [107]:
np.mean(a)

4.833333333333333

In [108]:
a.mean()

4.833333333333333

In [111]:
np.median(a)

5.0

In [112]:
np.percentile(a, 50)

5.0

In [113]:
np.percentile(a, 25)

3.5

In [114]:
np.percentile(a, 75)

5.75

## Polynomal

Linear : $y = ax + b$

Quadratic: $y = ax^2 + bx + c$

In [124]:
x = np.linspace(-10, 10, 200)

In [125]:
f = np.poly1d((2, 5, 4))

In [126]:
y = f(x)

In [127]:
plt.plot(x, y)
plt.show()

## Random

In [137]:
x = np.random.randn(1000)*10 + 180
x

array([178.69515397, 176.31481142, 183.76832598, 173.30226007,
       169.68390415, 167.76416994, 182.35715   , 175.40898784,
       179.62487779, 165.12694984, 198.31076221, 176.59215   ,
       174.68324574, 175.15209953, 168.13994426, 178.51612751,
       168.40363508, 181.13281187, 186.33779957, 183.67789236,
       172.55448971, 194.21429924, 161.57510771, 184.81020085,
       180.50973346, 173.07541063, 164.41946324, 190.12781304,
       194.91697872, 165.84414043, 164.42422207, 187.70894935,
       182.90683307, 170.23120061, 172.4775397 , 167.28707529,
       179.71643354, 168.60123564, 198.84645294, 167.47383682,
       177.63565022, 200.42119579, 178.72665201, 168.5545055 ,
       175.3199825 , 171.84788327, 177.81456969, 178.68389809,
       203.05985645, 167.31744227, 185.03265273, 186.94545621,
       182.64725384, 171.09902665, 183.06181069, 170.24002879,
       183.94761595, 170.69938809, 171.20288151, 167.79382459,
       180.45575987, 176.19011342, 194.67536038, 183.04

In [138]:
plt.hist(x, bins = 20)
plt.show()